version: "3"

services: 
    app:
        container_name: mediapipe-api
        build: .
        working_dir: /app
        ports:
            - "5000:5000" # Default
            - "8080:8080" # Production
            - "3000:3000" # Development
        command: ["python3", "src/app.py"]
